### PR TITLE
Adding new VT100 CSI Escapes

### PR DESCRIPTION
**Pull request by abaffa**
. Blinking interval adjusted to 525ms (similar time interval to vt100 terminal text blinking)

. Added New VT100 CSI Escapes:

\ESC [ ? 7 h		Wraparound ON
\ESC [ ? 7 l		Wraparound OFF

\ESC [ ? 12 h		Text Cursor Enable Blinking
\ESC [ ? 12 l	    Text Cursor Disable Blinking
 
\ESC [ 5 m		Blink ON
\ESC [ 25 m		Blink OFF

\ESC [ <n> @		Insert Character	Insert <n> spaces at the current cursor position, shifting all existing text to the right. Text exiting the screen to the right is removed.
\ESC [ <n> P		Delete Character	Delete <n> characters at the current cursor position, shifting in space characters from the right edge of the screen.
\ESC [ <n> X		Erase Character	Erase <n> characters from the current cursor position by overwriting them with a space character.

 
. Cursor Types
\ESC [ 0 SP q	User Shape	Default cursor shape configured by the user
\ESC [ 1 SP q	Blinking Block	Blinking block cursor shape
\ESC [ 2 SP q	Steady Block	Steady block cursor shape
\ESC [ 3 SP q	Blinking Underline	Blinking underline cursor shape
\ESC [ 4 SP q	Steady Underline	Steady underline cursor shape
\ESC [ 5 SP q	Blinking Bar	Blinking bar cursor shape
\ESC [ 6 SP q	Steady Bar	Steady bar cursor shape

* SP = space character

. DEC Line Drawing
\ESC ( 0	Designate Character Set – DEC Line Drawing	Enables DEC Line Drawing Mode - single line
\ESC ( 2	Designate Character Set – DEC Line Drawing	Enables DEC Line Drawing Mode - double line

	Hex	ASCII	DEC Line Drawing
	0x6a	j	┘
	0x6b	k	┐
	0x6c	l	┌
	0x6d	m	└
	0x6e	n	┼
	0x71	q	─
	0x74	t	├
	0x75	u	┤
	0x76	v	┴
	0x77	w	┬
	0x78	x	│

\ESC ( B	Designate Character Set – US ASCII	Enables ASCII Mode (Default)

----
References:

- http://matthieu.benoit.free.fr/68hc11/vt100.htm
- https://espterm.github.io/docs/VT100%20escape%20codes.html
- https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences
- https://vt100.net/docs/

### CODE REVIEW

**Comment by mchobby** [comment]
@abaffa thanks for this new share, I will manage it next week-end.
I do see some DEC related ESC sequence. Are you working on some old-time computer?

**Comment by abaffa** [comment]
@mchobby no, I'm working on a RC2014 compatible project. But, this is not the reason for including the DEC Graphic ESC sequences. It's a common VT100/VT220 escape for adding a shortcut to draw single or double borders. I've been testing on some BBSs using kermit to test and find out what I can improve :D  I'm also thinking in include a beeper using a buzzer attached to an empty pin. Also, it would be nice if we could add a option to choose between NuPETSCII and CP431 characters.

DEC Special Graphics Character Set are escapes to change the character table.

https://github.com/dariomas/vterm/blob/master/VT100.h
https://vt100.net/docs/vt220-rm/chapter2.html#T2-4

_Esc(A 	Set United Kingdom G0 character set 	setukg0
Esc)A 	Set United Kingdom G1 character set 	setukg1_
**Esc(B 	Set United States G0 character set 	setusg0**
_Esc)B 	Set United States G1 character set 	setusg1_
**Esc(0 	Set G0 special chars. & line set 	setspecg0**
_Esc)0 	Set G1 special chars. & line set 	setspecg1
Esc(1 	Set G0 alternate character ROM 	setaltg0
Esc)1 	Set G1 alternate character ROM 	setaltg1_
**Esc(2 	Set G0 alt char ROM and spec. graphics 	setaltspecg0**
_Esc)2 	Set G1 alt char ROM and spec. graphics 	setaltspecg1_


* Just implemented ESC(0 for single borders, ESC(2 for double borders and ESC(B for disable it - any other ESC(x will also disable graphic mode. It uses petscii and replaces some chars from k-z with border symbols. Maybe I should use ESC(0 and ESC)0 instead of ESC(2.

There are other escapes I think would be interesting:

Esc[?5h 	Set reverse video on screen 
Esc[?5l 	Set normal video on screen

Esc[?2l 	Set VT52 (versus ANSI)  -- enable VT52 ESCx escapes

Esc[20l 	Set line feed mode
Esc[20h 	Set new line mode 

EscH 	Set a tab at the current column 	(this is a vt52 ESCx - there is no [ . VT100 had a retrocompatibility to vt52).
Esc[g 	Clear a tab at the current column 	
Esc[0g 	Clear a tab at the current column 	
Esc[3g 	Clear all tabs

**Comment by mchobby** [comment]
@abaffa 
### CP431 charset
I will check for CP431 charset after merging your work (I had multi-font in mind since a while).

### Buzzer
Great idea, the GP22 can be used for that. I can assist you with this as needed.
To resume GPIO availability (I will document them also)
- GP28 is used to debug serial line (TX)
- GP27 should be preserve for a potential RX
- GP5 is used to delay USB Keyboard power-up (I'm currently testing it with USB-A female connector).
- GP18 & GP19 can be used as I2C (so should be preserved)
- GP26 have an Analog input function (so should be preserved).
- **GP22 have PWM then should be an ideal choice for Buzzer.**
-

**Comment by RFC2795** [comment]
Before you go using GP22 for the buzzer, I should probably let you in on a new "backpack" PCB which I am expecting to be delivered before Christmas.

GP5, GP18, GP19 and GP22 are going to be used for a Micro SD card to add additional storage (config files, fonts, sprites, whatever?)

The only free pins, which are bought out on the edge of that module, are GP26, GP27 and Gp28.

I'm happy to send both of you a board when they arrive and I know they work

**Comment by abaffa** [comment]
well... considering the pins listed by @mchobby and the new PCB, I guess the best option is use G27 for the buzzer. I'll add an active buzzer just to do the "beeps" in next days. 

@RFC2795 pls, send a picture of the pcb when it arrives :)

**Comment by mchobby** [comment]
@RFC2795 , @abaffa 
OK, I will use the GP26 for my USB Power-UP and GP27 for Buzzer TEMPORARILY (I will later assign them to I2C1 with a GPIO expander to expand capability of PicoTerm board and expansion boards).

Do you agree on this ?
GP18 : SDReader (function ???)
GP19 : SDReader (function ???)
GP5 : SDReader (function ???)
GP22: SDReader (function ???)
GP26 : I2C1 SDA (temporarily used for USB power-Up, I catched the Keyboard detection issue at power-up :-) )
GP27 : I2C1 SCL (temporarily used for Buzzer)
GP28 : Poor man debug_print() 

If so then it will start to document the GPIO behavior within the PicoTerm documentation.

**Comment by RFC2795** [comment]
Here is the schematic, and the 3D render of the PCB.  

Note that until I get the boards delivered and tested, this is only provisional information.  It is a very simple circuit though, so unless I've don't something really stupid, it should work.

[edit] The circuit is based on the hardware design guide from Raspberry Pi https://datasheets.raspberrypi.com/rp2040/hardware-design-with-rp2040.pdf

The intention is that this will sit on the back of the Pi Pico VGA Module with header pins, sandwiching the components between the 2 PCBs

It should be easy enough to remake this with an added buzzer on it.

Screenshot from 2022-12-20 10-21-33
Screenshot from 2022-12-20 10-22-23

**Comment by mchobby** [comment]
@abaffa 
Hi
I notice that cursor is not moved with Scroll-Up (  \ESC[nS  ). It is perhaps an espected behavior (or not).
At first sight, I can't find documentation about  \ESC[nS or \ESC[S .
1) Should cursor be moved accordingly ?
2) A documentation reference would be welcome.

I will update documentation accordingly.

**Comment by abaffa** [comment]
Hi @mchobby ,
 
Yes, i'ts expected. 

I tested it for the first time in tera term but it didn't convince me xD. Then I searched for some information and could find the standard for it in https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Functions-using-CSI-_-ordered-by-the-final-character_s_

	"CSI Ps S  Scroll up Ps lines (default = 1) (SU), VT420, ECMA-48."

So, on ECMA-48 (1991 5th edition) https://www.ecma-international.org/wp-content/uploads/ECMA-48_5th_edition_june_1991.pdf it says:

	8.3.147 SU - SCROLL UP
	...
	"The active presentation position is not affected by this control function"

**Comment by mchobby** [comment]
> Hi @mchobby ,
> 
> Yes, i'ts expected.
> 
> I tested it for the first time in tera term but it didn't convince me xD. Then I searched for some information and could find the standard for it in https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Functions-using-CSI-_-ordered-by-the-final-character_s_
> 
> ```
> "CSI Ps S  Scroll up Ps lines (default = 1) (SU), VT420, ECMA-48."
> ```
> 
> So, on ECMA-48 (1991 5th edition) https://www.ecma-international.org/wp-content/uploads/ECMA-48_5th_edition_june_1991.pdf it says:
> 
> ```
> 8.3.147 SU - SCROLL UP
> ...
> "The active presentation position is not affected by this control function"
> ```

Thanks for answer --> Documented

**Comment by mchobby** [comment]
@abaffa 
Finished tests for this former pull-request. You made a very great job on ESC sequence support.
__I get a final issue with DEC lines__: I can't get them on the display (was it already implemented in the former pull ?)
NB: test-suite and readme have been pushed on the repository

**Comment by abaffa** [comment]
do you mean Graphical DEC? yes, ... it's only ESC ( 0  without using "["... just ESC(0 or ESC(2

**Pull request merged**
