### PR TITLE
. Adding few more VT100 ESCapes

### PR DESCRIPTION
**Pull request by abaffa**
* VT52 escapes are included on VT100 terminal
* Added Query/Answer escapes used to identify terminal - after this BBSs are able to detect screen type and size.
* Added secondary screen buffer ESC[?47l and ESC[?47h
* added ESC[?1047l, ESC[?1049l and ESC[?1047h, ESC[?1049h used by linux to switch between main and secondary buffer

----------------

VT100 Escapes

	ESCc		reset settings
	
	ESC[?47l	restore screen
	ESC[?47h	save screen
	
	
	ESC[c		ask VT100ID
	ESC[0c		ask VT100ID
	ESC[5n		ask VT100 Status
	ESC[?2l  	enter VT52 mode
	
	
VT52 escapes  (available on VT100)

	ESC A           Cursor up
	ESC B           Cursor down
	ESC C           Cursor right
	ESC D           Cursor left
	ESC F           Special graphics character set
	ESC G           Select ASCII character set
	ESC H           Cursor to home
	ESC I           Reverse line feed
	ESC J           Erase to end of screen
	ESC K           Erase to end of line
	ESC Z           Identify
	ESC [Z          Identify
	ESC <           enter VT100 mode

### CODE REVIEW

**Comment by abaffa** [comment]
... I'm waiting for the buzzer to be delivered and then I'll add/finish the "bell" function

**Comment by mchobby** [comment]
@abaffa 
Currently writing test for the previous ones. Must be finish before merging this new share.
created issue #20 for separate the discussion about Buzzer.

**Comment by mchobby** [comment]
@abaffa 
I started to test the new escape sequence.
In the description the sentence "VT52 escapes (available on VT100)" means that VT52 sequence should also been executed when the terminal is in the VT100 mode. It is how I do understand it.
A'm I right ?

**Comment by abaffa** [comment]
> @abaffa 
> I started to test the new escape sequence.
> In the description the sentence "VT52 escapes (available on VT100)" means that VT52 sequence should also been executed when the terminal is in the VT100 mode. It is how I do understand it.
> A'm I right ? 

No, vt100 terminal has retrocompatibility but it's necessary to use an escape to enable it.

ESC[?2l enables vt52 escapes mode (on vt100 terminal). During vt52 mode only reset ( ESC[c  -      I think) and vt52 escapes are recognized.

if u're on vt52 mode, u can return to vt100 mode using ESC <

**Comment by mchobby** [comment]
Great, it is the exact behavior as I tested it.
I'd also like the screen buffering. This will helps a lot.
You have made an amazing job with those additional escapes sequences. Thanks!

**Comment by mchobby** [comment]
I notice that ESC F and ESC G have been rewritten... which completely disabled the NuPetScii implementation (and existing examples).
As NuPetScii also contains the DEC simple line and double line drawing, would it be possible to translate the DEC instruction to appropriate NuPetScii chars?

After some thinking, ESC F & ESC G should activate NupetScii.... which should be overseed by DEC mode only when \ESC(0 or \ESC(2 is received after Graphical instruction.

What do you think about that?

**Comment by abaffa** [comment]
Yes... about that,  I commented the ESC F & G lines and forgot to ask about it.  I agree with you. The DEC Graphical mode uses the NupetScii "border" symbols when you type chars j, k, l, m, n, q, t, u, v, w and x, and should be enabled only by \ESC(0 and \ESC(2.

ps: I'm not sure if it was your question on pull#17 - but dec graphical mode escape does not use [ symbol.. its only "ESC(0" or "ESC(2"

**Comment by mchobby** [comment]
@abaffa 
I'm almost done with the DEC line implementation 
Sélection_041
Will fix char assignation and make a full round of test.

**Comment by mchobby** [comment]
Pushed the latest version :-) 
Will now work on alternate font

**Pull request merged**
